#!/usr/bin/env python3
"""Regenerate docs/BASELINE_TABLE.md + docs/RESULTS_SUMMARY.md from baseline_matrix.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JSON = ROOT / "outputs/scheme_l3/baseline_matrix.json"

PASS = {
    "lat_min_median_mm": 14.0,
    "along_mean_mm": 90.0,
    "force_peak_n": 0.5,
    "slip_mm": 30.0,
    "enter_rate": 0.5,
}

HIGHLIGHT_EPS = (3, 4, 5, 8)
TIER_ORDER = {"neg": 0, "A": 1, "B": 2, "B'": 3, "C-α": 4, "C": 5}


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def fmt_lat(a: dict) -> str:
    if not a.get("n"):
        return "—"
    return f"med {a['lat_min_median']:.1f} / mean {a['lat_min_mean']:.1f}"


def aggregate_table(agg: list[dict], best_lat: float) -> list[str]:
    lines = [
        "| Tier | Method | lat_min ↓ (mm) | along ↓ (mm) | |F|_peak ↓ (N) | slip ↓ (mm) | enter rate | n |",
        "|------|--------|----------------|--------------|---------------|-------------|------------|---|",
    ]
    for a in sorted(agg, key=lambda x: TIER_ORDER.get(x.get("tier", ""), 99)):
        if not a.get("n"):
            lines.append(f"| {a['tier']} | {a['label']} | — | — | — | — | — | 0 |")
            continue
        star = " **" if a["lat_min_median"] <= best_lat + 0.01 else ""
        lines.append(
            f"| {a['tier']} | {a['label']} | "
            f"{fmt_lat(a)}{star} | "
            f"{a['along_mean']:.1f} | {a['force_peak_mean']:.2f} | "
            f"{a['slip_mean']:.0f} | {100 * a['enter_rate']:.0f}% | {a['n']} |"
        )
    return lines


def per_episode_table(detail: list[dict]) -> list[str]:
    lines = [
        "| ep | scheme | lat_min | along | |F|_pk | enter | reason |",
        "|----|--------|---------|-------|-------|-------|--------|",
    ]
    for r in sorted(detail, key=lambda x: (x.get("episode", 0), x.get("id", ""))):
        if r.get("status") != "ok":
            lines.append(
                f"| {r.get('episode', '?'):02d} | {r.get('id', '?')} | FAIL | — | — | — | {r.get('status')} |"
            )
            continue
        ent = "Y" if (r.get("priv_enter") or r.get("mouth_ok")) else "N"
        lines.append(
            f"| {r['episode']:02d} | {r['id']} | {r['lat_min_mm']:.1f} | "
            f"{r['final_along_mm']:.1f} | {r['resid_peak_n']:.2f} | {ent} | {r.get('spiral_reason', '')} |"
        )
    return lines


def highlight_table(detail: list[dict]) -> list[str]:
    rows = [r for r in detail if r.get("status") == "ok" and r.get("episode") in HIGHLIGHT_EPS]
    lines = [
        "| ep | scheme | lat_min | along | |F|_pk | enter | reason |",
        "|----|--------|---------|-------|-------|-------|--------|",
    ]
    for r in sorted(rows, key=lambda x: (x["episode"], x.get("id", ""))):
        ent = "Y" if (r.get("priv_enter") or r.get("mouth_ok")) else "N"
        lines.append(
            f"| {r['episode']:02d} | {r['id']} | {r['lat_min_mm']:.1f} | "
            f"{r['final_along_mm']:.1f} | {r['resid_peak_n']:.2f} | {ent} | {r.get('spiral_reason', '')} |"
        )
    return lines


def best_by(agg: list[dict], key: str, lower: bool = True) -> dict | None:
    ok = [a for a in agg if a.get("n")]
    if not ok:
        return None
    return min(ok, key=lambda a: a[key]) if lower else max(ok, key=lambda a: a[key])


def pass_row(name: str, target: str, actual: str, met: bool) -> str:
    mark = "✓" if met else "✗"
    return f"| {name} | {target} | {actual} | {mark} |"


def baseline_md(agg: list[dict], detail: list[dict]) -> str:
    best_lat = min((a["lat_min_median"] for a in agg if a.get("n")), default=999.0)
    lines = [
        "# Baseline Comparison Table (auto-generated)",
        "",
        "> **Scheme note:** **S7** (`planar_coupling`) 为已弃用 patch，表内 Tier C 行仍为其 ep01–10 结果；"
        "论文拟用 **S8 planar_C**（planar coupling matrix + along 约束，尚未跑完/未入表）。",
        "",
        "## Aggregate (handoff grasp, DexJoCo PCI)",
        "",
        *aggregate_table(agg, best_lat),
        "",
        "## Per-episode",
        "",
        *per_episode_table(detail),
        "",
        "_Generated by `scripts/export_paper_tables.py`_",
    ]
    return "\n".join(lines)


def results_summary_md(agg: list[dict], detail: list[dict]) -> str:
    best_lat = best_by(agg, "lat_min_median")
    best_along = best_by(agg, "along_mean")
    best_force = best_by(agg, "force_peak_mean")
    best_enter = best_by(agg, "enter_rate", lower=False)
    s3 = next((a for a in agg if a.get("id") == "S3"), {})
    s2 = next((a for a in agg if a.get("id") == "S2"), {})
    s7 = next((a for a in agg if a.get("id") == "S7"), {})

    def chk(a: dict | None, key: str, limit: float, lower: bool = True) -> bool:
        if not a or not a.get("n"):
            return False
        v = a[key]
        return v <= limit if lower else v >= limit

    s7_pass = [
        pass_row(
            "lat_min median (mm)",
            f"≤ {PASS['lat_min_median_mm']:.0f}",
            f"{s7.get('lat_min_median', float('nan')):.1f}" if s7.get("n") else "—",
            chk(s7, "lat_min_median", PASS["lat_min_median_mm"]),
        ),
        pass_row(
            "along mean (mm)",
            f"≤ {PASS['along_mean_mm']:.0f}",
            f"{s7.get('along_mean', float('nan')):.1f}" if s7.get("n") else "—",
            chk(s7, "along_mean", PASS["along_mean_mm"]),
        ),
        pass_row(
            "|F|_peak mean (N)",
            f"≤ {PASS['force_peak_n']:.1f}",
            f"{s7.get('force_peak_mean', float('nan')):.2f}" if s7.get("n") else "—",
            chk(s7, "force_peak_mean", PASS["force_peak_n"]),
        ),
        pass_row(
            "grasp slip mean (mm)",
            f"≤ {PASS['slip_mm']:.0f}",
            f"{s7.get('slip_mean', float('nan')):.0f}" if s7.get("n") else "—",
            chk(s7, "slip_mean", PASS["slip_mm"]),
        ),
        pass_row(
            "enter rate",
            f"≥ {PASS['enter_rate'] * 100:.0f}%",
            f"{100 * s7.get('enter_rate', 0):.0f}%" if s7.get("n") else "—",
            chk(s7, "enter_rate", PASS["enter_rate"], lower=False),
        ),
    ]

    best_lat_pass = [
        pass_row(
            "lat_min median (mm)",
            f"≤ {PASS['lat_min_median_mm']:.0f}",
            f"{best_lat['lat_min_median']:.1f} ({best_lat['id']})" if best_lat else "—",
            chk(best_lat, "lat_min_median", PASS["lat_min_median_mm"]) if best_lat else False,
        ),
        pass_row(
            "along mean (mm)",
            f"≤ {PASS['along_mean_mm']:.0f}",
            f"{best_along['along_mean']:.1f} ({best_along['id']})" if best_along else "—",
            chk(best_along, "along_mean", PASS["along_mean_mm"]) if best_along else False,
        ),
        pass_row(
            "enter rate",
            f"≥ {PASS['enter_rate'] * 100:.0f}%",
            f"{100 * best_enter['enter_rate']:.0f}% ({best_enter['id']})" if best_enter else "—",
            chk(best_enter, "enter_rate", PASS["enter_rate"], lower=False) if best_enter else False,
        ),
    ]

    s7_ep4 = next(
        (r for r in detail if r.get("id") == "S7" and r.get("episode") == 4 and r.get("status") == "ok"),
        None,
    )

    lines = [
        "# L3 Baseline 结果摘要",
        "",
        "> 来源：`outputs/scheme_l3/baseline_matrix.json`（ep01–10，handoff grasp）",
        "",
        "## 科学结论",
        "",
        f"- **问题成立**：非刚性抓握下腕螺旋 ≠ tip 接触轨迹；ConnTact（S3）median lat_min={s3.get('lat_min_median', 999):.0f} mm、进孔 0%，证实 rigid-EE 假设不成立。",
        f"- **ConnTact 失败**：S3 沿向漂移最大（along mean {s3.get('along_mean', 0):.1f} mm），力峰值近 0（未有效贴面搜孔），10/10 ep 无进孔。",
        f"- **tip-reference 方向对**：S2 live offset 将 median lat 压至 {s2.get('lat_min_median', 0):.1f} mm（全表最优），S6/S7 亦 ~14 mm，优于 S0/S1 与 S3。",
        f"- **along 未解决**：各方案 along mean 仍 {min(a['along_mean'] for a in agg if a.get('n')):.0f}–{max(a['along_mean'] for a in agg if a.get('n')):.0f} mm（目标 ≤{PASS['along_mean_mm']:.0f}），尖端正向未沉入孔口。",
        f"- **S7 patch 有限**：唯一进孔 ep04（lat={s7_ep4['lat_min_mm']:.1f} mm，enter=Y）使 enter rate={100 * s7.get('enter_rate', 0):.0f}%，但 slip 升至 {s7.get('slip_mean', 0):.0f} mm；**S8 planar_C** 待验证。",
        "",
        "## 汇总表（Aggregate）",
        "",
        *aggregate_table(agg, min((a["lat_min_median"] for a in agg if a.get("n")), default=999.0)),
        "",
        "## 论文 Figure / Table 建议",
        "",
        "- **Table 1（主表）**：上表 Aggregate，列 Tier / Method / lat_min / along / |F|_peak / slip / enter rate；S0 负基线 + S3 ConnTact + S1/S2 tip-reference + S6 ablation；S7 标注 deprecated，S8 占位 TBD。",
        "- **Table 2（个案）**：ep03/04/05/08 分 scheme 明细（见下）；ep04 突出 S7 唯一进孔，ep03 对比 S2 lat 优但 timeout，ep08 代表 tilt/slip 主失败模态。",
        "- **Fig 1**：问题示意——ConnTact 腕螺旋 vs tip-referenced spiral； grasp slip 导致 wedge/抬离。",
        "- **Fig 2**：ep08 轨迹/力曲线叠图（S0 vs S2 vs S3），展示 lateral 改善与 along 停滞。",
        "- **Fig 3（可选）**：ep04 S7 进孔 vs ep04 S2 近口失败，对比 along 与 priv_enter 时序。",
        "",
        "### Table 2 候选行（ep03/04/05/08）",
        "",
        *highlight_table(detail),
        "",
        "## Pass criteria vs actual",
        "",
        "阈值来自 `priv_planned_spiral_autorun`（lat<14、drift<8）与 L3 score（进孔加权）；along≤90 mm 对应孔口沉入。",
        "",
        "### S7（deprecated patch）",
        "",
        "| 指标 | 目标 | S7 实际 | 达标 |",
        "|------|------|---------|------|",
        *s7_pass,
        "",
        "### 全表最优",
        "",
        "| 指标 | 目标 | 最优实际 | 达标 |",
        "|------|------|----------|------|",
        *best_lat_pass,
        "",
        f"_Best force: {best_force['force_peak_mean']:.2f} N ({best_force['id']})；best along: {best_along['along_mean']:.1f} mm ({best_along['id']})._",
        "",
        "_Generated by `scripts/export_paper_tables.py`_",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", type=Path, default=DEFAULT_JSON)
    ap.add_argument("--baseline-out", type=Path, default=ROOT / "docs/BASELINE_TABLE.md")
    ap.add_argument("--summary-out", type=Path, default=ROOT / "docs/RESULTS_SUMMARY.md")
    args = ap.parse_args()

    data = load(args.json)
    agg = data["aggregate"]
    detail = data["detail"]

    args.baseline_out.parent.mkdir(parents=True, exist_ok=True)
    args.baseline_out.write_text(baseline_md(agg, detail), encoding="utf-8")
    args.summary_out.write_text(results_summary_md(agg, detail), encoding="utf-8")

    print(f"Wrote {args.baseline_out}")
    print(f"Wrote {args.summary_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
